* Encoding: UTF-8.
*multinomial logistic regression syntax

NOMREG DVgroup (BASE=LAST ORDER=ASCENDING) WITH IV 
  /CRITERIA CIN(95) DELTA(0) MXITER(100) MXSTEP(5) CHKSEP(20) LCONVERGE(0) PCONVERGE(0.000001) 
    SINGULAR(0.00000001) 
  /MODEL 
  /STEPWISE=PIN(.05) POUT(0.1) MINEFFECT(0) RULE(SINGLE) ENTRYMETHOD(LR) REMOVALMETHOD(LR) 
  /INTERCEPT=INCLUDE 
  /PRINT=PARAMETER SUMMARY LRT CPS STEP MFI.
